name: "Scan Virus"
author: "hugoalh"
description: "Scan virus (including malicious file and malware) in the GitHub Action workspace."
inputs:
  input_list_delimiter:
    description: "{RegEx} Delimiter when the input is type of list."
    required: false
    default: ",|;|\\r?\\n"
  input_table_markup:
    description: "{String} Markup language when the input is type of table."
    required: false
    default: "yaml"
  targets:
    description: "{Uri[]} Targets."
    required: false
  git_integrate:
    description: "{Boolean} Whether to integrate with Git to perform scan by the commits."
    required: false
    default: "False"
  git_include_allbranches:
    description: "{Boolean} Whether to include the Git commits which not in the current branch."
    required: false
    default: "False"
  git_include_reflogs:
    description: "{Boolean} Whether to include the Git commits which marked as references."
    required: false
    default: "False"
  git_reverse:
    description: "{Boolean} Whether to reverse the scan order of the Git commits."
    required: false
    default: "False"
  clamav_enable:
    description: "{Boolean} Whether to use ClamAV."
    required: false
    default: "True"
  clamav_unofficialassets:
    description: "{RegEx[]} ClamAV unofficial assets to use."
    required: false
  yara_enable:
    description: "{Boolean} Whether to use YARA."
    required: false
    default: "False"
  yara_unofficialassets:
    description: "{RegEx[]} YARA unofficial assets to use."
    required: false
  update_clamav:
    description: "{Boolean} Whether to update the ClamAV official assets via FreshClam before scan anything."
    required: false
    default: "True"
  ignores_elements:
    description: "{Table} Ignores for the paths, rules (YARA), sessions, and/or signatures (ClamAV)."
    required: false
  ignores_gitcommits_meta:
    description: "{Table} Ignores for the Git commits meta."
    required: false
  ignores_gitcommits_nonnewest:
    description: "{UInt} Ignores for the non newest Git commits."
    required: false
    default: "0"
runs:
  using: "docker"
  image: "docker://ghcr.io/hugoalh/scan-virus-ghaction:0.10.0"
branding:
  icon: "shield"
  color: "red"
