name: "Scan Virus"
author: "hugoalh"
description: "Scan virus in the GitHub Action workspace."
inputs:
  targets:
    description: "{string[]} Targets."
    required: false
    default: "./"
  git_deep:
    description: "{boolean} Scan deeper for Git repository."
    required: false
    default: "false"
  git_reversesession:
    description: "{boolean} Reverse Git session."
    required: false
    default: "false"
  clamav_enable:
    description: "{boolean} Use ClamAV."
    required: false
    default: "true"
  clamav_daemon:
    description: "{boolean} Use ClamAV daemon."
    required: false
    default: "true"
  clamav_filesfilter_list:
    description: "{string[]} ClamAV files filter list."
    required: false
    default: ""
  clamav_filesfilter_mode:
    description: "{string} ClamAV files filter mode."
    required: false
    default: "exclude"
  clamav_multiscan:
    description: "{boolean} Use ClamAV multiscan mode."
    required: false
    default: "true"
  clamav_reloadpersession:
    description: "{boolean} Reload ClamAV per session."
    required: false
    default: "false"
  clamav_signaturesignore_custom:
    description: "{string[]} Ignore individual ClamAV signatures."
    required: false
    default: ""
  clamav_signaturesignore_presets:
    description: "{string[]} Ignore ClamAV signatures by presets list."
    required: false
    default: ""
  clamav_subcursive:
    description: "{boolean} Scan directories subcursively."
    required: false
    default: "true"
  clamav_unofficialsignatures:
    description: "{string[]} ClamAV unofficial signatures."
    required: false
    default: ""
  yara_enable:
    description: "{boolean} Use YARA."
    required: false
    default: "false"
  yara_filesfilter_list:
    description: "{string[]} YARA files filter list."
    required: false
    default: ""
  yara_filesfilter_mode:
    description: "{string} YARA files filter mode."
    required: false
    default: "exclude"
  yara_rulesfilter_list:
    description: "{string[]} YARA rules filter list."
    required: false
    default: ""
  yara_rulesfilter_mode:
    description: "{string} YARA rules filter mode."
    required: false
    default: "exclude"
  yara_toolwarning:
    description: "{boolean} Enable YARA tool warning."
    required: false
    default: "false"
runs:
  using: "docker"
  image: "docker://ghcr.io/hugoalh/scan-virus-ghaction:0.6.1"
branding:
  icon: "shield"
  color: "red"
