name: "Scan Virus"
author: "hugoalh"
description: "Scan virus in the GitHub Action workspace."
inputs:
  input_listdelimiter:
    description: "{String} Delimiter when input is support multiple values."
    required: false
    default: ";|\\r?\\n"
  targets:
    description: "{String[]} Targets."
    required: false
    default: "./"
  git_deep:
    description: "{Boolean} Scan deeper for Git repository by each commits."
    required: false
    default: "false"
  git_reverse:
    description: "{Boolean} Reverse sort order of Git commits."
    required: false
    default: "false"
  clamav_enable:
    description: "{Boolean} Use ClamAV."
    required: false
    default: "true"
  clamav_daemon:
    description: "{Boolean} Use ClamAV daemon."
    required: false
    default: "true"
  clamav_filesfilter:
    description: "{String[]} ClamAV files filter."
    required: false
    default: ""
  clamav_multiscan:
    description: "{Boolean} Use ClamAV multiscan mode."
    required: false
    default: "true"
  clamav_reloadpersession:
    description: "{Boolean} Reload ClamAV per session."
    required: false
    default: "false"
  clamav_resultsfilter:
    description: "{String[]} ClamAV results filter."
    required: false
    default: ""
  clamav_subcursive:
    description: "{Boolean} Scan directories subcursively."
    required: false
    default: "true"
  clamav_unofficialsignatures:
    description: "{String[]} Use ClamAV unofficial signatures."
    required: false
    default: |
      -^.+$
  yara_enable:
    description: "{Boolean} Use YARA."
    required: false
    default: "false"
  yara_filesfilter:
    description: "{String[]} YARA files filter."
    required: false
    default: ""
  yara_resultsfilter:
    description: "{String[]} YARA results filter."
    required: false
    default: ""
  yara_rules:
    description: "{String[]} Use YARA rules."
    required: false
    default: ""
  yara_toolwarning:
    description: "{Boolean} Enable YARA tool warning."
    required: false
    default: "false"
runs:
  using: "docker"
  image: "docker://ghcr.io/hugoalh/scan-virus-ghaction:0.7.0"
branding:
  icon: "shield"
  color: "red"
