name: "Scan Virus"
author: "hugoalh"
description: "Scan virus in the GitHub Action workspace."
inputs:
  input_listdelimiter:
    description: "{RegEx} Delimiter when input is type of list (i.e.: array)."
    required: false
    default: ",|;|\\r?\\n"
  input_tableparser:
    description: "{String} Paser to use when input is type of table."
    required: false
    default: "yaml"
  targets:
    description: "{Uri[]} Targets."
    required: false
  git_integrate:
    description: "{Boolean} Integrate with Git to scan every commits; Require workspace is a Git repository."
    required: false
    default: "False"
  git_ignores:
    description: "{Table<{String:RegEx}>} Git ignores (for commits)."
    required: false
  git_reverse:
    description: "{Boolean} Reverse scan order of the Git commits."
    required: false
    default: "False"
  clamav_enable:
    description: "{Boolean} Use ClamAV."
    required: false
    default: "True"
  clamav_daemon:
    description: "{Boolean} Use ClamAV daemon."
    required: false
    default: "True"
  clamav_ignores:
    description: "{Table<{String:RegEx}>} ClamAV ignores."
    required: false
  clamav_multiscan:
    description: "{Boolean} Use ClamAV multiscan mode."
    required: false
    default: "True"
  clamav_reloadpersession:
    description: "{Boolean} Reload ClamAV per session."
    required: false
    default: "False"
  clamav_subcursive:
    description: "{Boolean} Scan directories subcursively."
    required: false
    default: "True"
  clamav_unofficialsignatures:
    description: "{RegEx[]} Use ClamAV unofficial signatures."
    required: false
  yara_enable:
    description: "{Boolean} Use YARA."
    required: false
    default: "False"
  yara_ignores:
    description: "{Table<{String:RegEx}>} YARA ignores."
    required: false
  yara_rules:
    description: "{RegEx[]} Use YARA rules."
    required: false
  yara_toolwarning:
    description: "{Boolean} Enable YARA tool warning."
    required: false
    default: "False"
  update_assets:
    description: "{Boolean} Update ClamAV unofficial signatures and YARA rules from assets repository before scan anything."
    required: false
    default: "True"
  update_clamav:
    description: "{Boolean} Update ClamAV official signatures via FreshClam before scan anything."
    required: false
    default: "True"
runs:
  using: "docker"
  image: "docker://ghcr.io/hugoalh/scan-virus-ghaction:0.10.0-alpha.1"
branding:
  icon: "shield"
  color: "red"
