name: "Scan Virus (YARA)"
author: "hugoalh"
description: "Scan virus (including malicious file and malware)."
inputs:
  yara_unofficialassets_use:
    description: "{RegExp[]} YARA unofficial assets to use."
    required: false
  yara_customassets_artifact:
    description: "{number} Artifact ID of the YARA custom assets."
    required: false
  yara_customassets_use:
    description: "{RegExp[]} YARA custom assets to use."
    required: false
    default: ".+"
  git_integrate:
    description: "{boolean} Whether to integrate with Git to perform scan by every commits."
    required: false
    default: "false"
  git_ignores:
    description: "{function} Ignores by the Git commits."
    required: false
  git_lfs:
    description: "{boolean} Whether to process Git LFS files."
    required: false
    default: "false"
  git_limit:
    description: "{bigint} Limit on how many Git commits will scan."
    required: false
    default: "0"
  git_reverse:
    description: "{boolean} Whether to reverse the scan order of the Git commits."
    required: false
    default: "false"
  ignores_pre:
    description: "{function} Ignores by the paths, sessions, and tools before the scan."
    required: false
  ignores_post:
    description: "{function} Ignores by the paths, sessions, symbols (i.e. rules or signatures), and tools after the scan."
    required: false
  summary:
    description: "{boolean} Whether to generate summary."
    required: false
    default: "false"
outputs:
  finish:
    description: "{boolean} Whether this action correctly finished without non catch issues."
  found:
    description: "{boolean} Whether there has element which found virus."
runs:
  using: "docker"
  image: "docker://ghcr.io/hugoalh/scan-virus-ghaction:0.30.0-yara"
branding:
  icon: "shield"
  color: "red"
