name: "Scan Virus"
author: "hugoalh"
description: "Scan virus in the GitHub Action workspace."
inputs:
  input_listdelimiter:
    description: "{RegEx} Delimiter when input is type of list (i.e.: array)."
    required: false
    default: ";|\\r?\\n"
  targets:
    description: "{Uri[]} Targets."
    required: false
    default: ""
  git_integrate:
    description: "{Boolean} Integrate with Git to scan every commits; Require workspace is a Git repository."
    required: false
    default: "False"
  git_reverse:
    description: "{Boolean} Reverse scan order of Git commits."
    required: false
    default: "False"
  clamav_enable:
    description: "{Boolean} Use ClamAV."
    required: false
    default: "True"
  clamav_daemon:
    description: "{Boolean} Use ClamAV daemon."
    required: false
    default: "True"
  clamav_filesfilter:
    description: "{String[]} ClamAV files filter."
    required: false
    default: ""
  clamav_multiscan:
    description: "{Boolean} Use ClamAV multiscan mode."
    required: false
    default: "True"
  clamav_reloadpersession:
    description: "{Boolean} Reload ClamAV per session."
    required: false
    default: "False"
  clamav_resultsfilter:
    description: "{String[]} ClamAV results filter."
    required: false
    default: ""
  clamav_subcursive:
    description: "{Boolean} Scan directories subcursively."
    required: false
    default: "True"
  clamav_unofficialsignatures:
    description: "{String[]} Use ClamAV unofficial signatures."
    required: false
    default: |
      -^.+$
  yara_enable:
    description: "{Boolean} Use YARA."
    required: false
    default: "False"
  yara_filesfilter:
    description: "{String[]} YARA files filter."
    required: false
    default: ""
  yara_resultsfilter:
    description: "{String[]} YARA results filter."
    required: false
    default: ""
  yara_rules:
    description: "{String[]} Use YARA rules."
    required: false
    default: ""
  yara_toolwarning:
    description: "{Boolean} Enable YARA tool warning."
    required: false
    default: "False"
runs:
  using: "docker"
  image: "../Dockerfile"
branding:
  icon: "shield"
  color: "red"
