name: "Scan Virus"
author: "hugoalh"
description: "Scan virus in the GitHub Action workspace."
inputs:
  input_list_delimiter:
    description: "{RegEx} Delimiter when the input is type of list."
    required: false
    default: ",|;|\\r?\\n"
  input_table_parser:
    description: "{String} Parser when the input is type of table."
    required: false
    default: "yaml"
  targets:
    description: "{Uri[]} Targets."
    required: false
  git_integrate:
    description: "{Boolean} Integrate with Git to scan every commits."
    required: false
    default: "False"
  git_ignores:
    description: "{Table} Ignores for the Git commits."
    required: false
  git_log_allbranches:
    description: "{Boolean} Include the Git commits which not in the default branch."
    required: false
    default: "False"
  git_log_reflogs:
    description: "{Boolean} Include the Git commits which marked as references."
    required: false
    default: "False"
  git_reverse:
    description: "{Boolean} Reverse the scan order of the Git commits."
    required: false
    default: "False"
  clamav_enable:
    description: "{Boolean} Use ClamAV."
    required: false
    default: "True"
  clamav_daemon:
    description: "{Boolean} Use ClamAV daemon."
    required: false
    default: "True"
  clamav_ignores:
    description: "{Table} Ignores for the ClamAV's paths, sessions, and/or signatures."
    required: false
  clamav_multiscan:
    description: "{Boolean} Use ClamAV multiscan mode."
    required: false
    default: "True"
  clamav_reloadpersession:
    description: "{Boolean} Reload ClamAV per session."
    required: false
    default: "False"
  clamav_subcursive:
    description: "{Boolean} Scan directories subcursively."
    required: false
    default: "True"
  clamav_unofficialsignatures:
    description: "{RegEx[]} Use ClamAV unofficial signatures."
    required: false
  yara_enable:
    description: "{Boolean} Use YARA."
    required: false
    default: "False"
  yara_ignores:
    description: "{Table} Ignores for the YARA's paths, rules, and/or sessions."
    required: false
  yara_rules:
    description: "{RegEx[]} Use YARA rules."
    required: false
  yara_toolwarning:
    description: "{Boolean} Enable YARA tool warning."
    required: false
    default: "False"
  update_assets:
    description: "{Boolean} Update ClamAV unofficial signatures and YARA rules from the assets repository before scan anything."
    required: false
    default: "True"
  update_clamav:
    description: "{Boolean} Update ClamAV official signatures via FreshClam before scan anything."
    required: false
    default: "True"
runs:
  using: "docker"
  image: "../../Dockerfile"
branding:
  icon: "shield"
  color: "red"
