name: "Publish Docker Container - GitHub Packages"
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tag:
        type: "string"
        description: "{string} Tag."
        required: true
      latest:
        type: "choice"
        description: "{boolean} Latest."
        required: false
        default: "false"
        options:
          - "false"
          - "true"
jobs:
  main:
    name: "Main"
    uses: "hugoalh/hugoalh/.github/workflows/publish-docker-container-ghp.yml@main"
    with:
      title: "Scan Virus (GitHub Action) Image"
      description: "A Docker image for Scan Virus (GitHub Action) to scan virus in the GitHub Action workspace."
      license: "MIT"
      tag: "${{github.event.inputs.tag}}"
      latest: "${{github.event.inputs.latest}}"
