# $<Schema>$ https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: "Scan Virus - Specify Repositories"
on:
  workflow_dispatch:
    inputs:
      repositories:
        description: "{string[]} GitHub repositories."
        required: true
      integrate_git:
        description: "{boolean} Git integration."
        required: false
        default: "true"
      list_elements:
        description: "{(number | string)} List elements."
        required: false
        default: "none"
      list_elementshashes:
        description: "{boolean} List elements' hashes under itself."
        required: false
        default: "false"
      list_miscellaneousresults:
        description: "{(number | string)} List miscellaneous results."
        required: false
        default: "none"
      list_scanresults:
        description: "{(number | string)} List scan results."
        required: false
        default: "none"
jobs:
  parse-inputs:
    name: "(Parse Inputs)"
    runs-on: "ubuntu-latest"
    steps:
      - run: |
          [string[]]$Repositories = '${{github.event.inputs.repositories}}'.Trim() -split '[ ,;]+'
          for ($Index = 0; $Index -lt $Repositories.Count; $Index++) {
            $Repositories[$Index] = $Repositories[$Index] -replace '^(?:https?:\/\/)?github\.com\/', ''
          }
          Write-Host -Object "::set-output name=matrix::{`"repositories`":[`"$($Repositories -join '","')`"]}"
          [bool]$GitIntegration = [bool]::Parse('${{github.event.inputs.integrate_git}}')
          Write-Host -Object "::set-output name=depth::$($GitIntegration ? 0 : 1)"
          Write-Host -Object "::set-output name=integrate::$($GitIntegration ? 'git' : 'none')"
          Write-Host -Object "::set-output name=title::$($GitIntegration ? 'Depth' : 'Flat')"
        id: "parser"
        shell: "pwsh"
    outputs:
      depth: "${{steps.parser.outputs.depth}}"
      integrate: "${{steps.parser.outputs.integrate}}"
      matrix: "${{steps.parser.outputs.matrix}}"
      title: "${{steps.parser.outputs.title}}"
  scan-virus-specify-repositories:
    name: "${{needs.parse-inputs.outputs.title}} Scan - ${{matrix.repositories}}"
    runs-on: "ubuntu-latest"
    needs:
      - "parse-inputs"
    strategy:
      fail-fast: false
      matrix: "${{fromJSON(needs.parse-inputs.outputs.matrix)}}"
    steps:
      - name: "Checkout Repository ${{matrix.repositories}}"
        uses: "actions/checkout@v3"
        with:
          repository: "${{matrix.repositories}}"
          fetch-depth: "${{needs.parse-inputs.outputs.depth}}"
          token: "${{secrets.GHP_SCANVIRUSCLONEREPOSITORY}}"
      - name: "${{needs.parse-inputs.outputs.title}} Scan Repository ${{matrix.repositories}}"
        uses: "hugoalh/scan-virus-ghaction@main"
        with:
          integrate: "${{needs.parse-inputs.outputs.integrate}}"
          list_elements: "${{github.event.inputs.list_elements}}"
          list_elementshashes: "${{github.event.inputs.list_elementshashes}}"
          list_miscellaneousresults: "${{github.event.inputs.list_miscellaneousresults}}"
          list_scanresults: "${{github.event.inputs.list_scanresults}}"
