name: "Scan Virus"
on:
  workflow_dispatch:
    inputs:
      git_deep:
        description: "{Boolean} Scan deeper for Git repository."
        required: false
        default: "true"
      git_reverse:
        description: "{Boolean} Reverse Git session."
        required: false
        default: "false"
jobs:
  scan-virus:
    name: "Scan Virus"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v3.0.2"
        with:
          fetch-depth: 0
      - name: "Scan Repository"
        uses: "hugoalh/scan-virus-ghaction@main"
        with:
          git_deep: "${{github.event.inputs.git_deep}}"
          git_reverse: "${{github.event.inputs.git_reverse}}"
