name: "Scan Virus - NPM"
on:
  workflow_dispatch:
    inputs:
      packages:
        type: "string"
        description: "{String[]} Packages."
        required: true
jobs:
  resolve-packages:
    name: "(Resolve Packages)"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Setup PowerShell Toolkit"
        uses: "hugoalh-studio/setup-powershell-toolkit-ghaction@v1.2.3"
      - name: "Resolve Packages"
        id: "resolve-packages"
        run: |
          Import-Module -Name 'hugoalh.GitHubActionsToolkit' -Scope 'Local'
          [String[]]$Packages = '${{github.event.inputs.packages}}' -isplit ',|;' |
            ForEach-Object -Process { $_.Trim() } |
            Where-Object -FilterScript { $_.Length -gt 0 } |
            Sort-Object -Unique
          [Hashtable[]]$Group = @()
          ForEach ($Package In $Packages) {
            [PSCustomObject]$PackageMeta = Invoke-WebRequest -Uri "https://registry.npmjs.org/$Package" -Headers @{ 'Content-Type' = 'application/json' } -MaximumRedirection 1 -MaximumRetryCount 2 -RetryIntervalSec 5 -Method 'Get' |
              Select-Object -ExpandProperty 'Content' |
              ConvertFrom-Json -Depth 100
            If ($PackageMeta.error -ieq 'Not found') {
              Write-GitHubActionsWarning -Message "``$Package`` is not found!"
            }
            [String[]]$PackageTarballUri = $PackageMeta.versions.PSObject.Properties.Value.dist.tarball
            $Group += @{
              name = $Package
              uris = $PackageTarballUri |
                Join-String -Separator "`n"
            }
          }
          Set-GitHubActionsOutput -Name 'group' -Value (
            $Group |
              ForEach-Object -Process {
                $_ |
                  ConvertTo-Json -Depth 100 -Compress
              } |
              ConvertTo-Json -Depth 100 -Compress
          )
        shell: "pwsh"
    outputs:
      group: "${{steps.resolve-packages.outputs.group}}"
  main:
    name: "${{fromJson(matrix.group).name}}"
    needs:
      - "resolve-packages"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        group: "${{fromJson(needs.resolve-packages.outputs.group)}}"
      fail-fast: false
    steps:
      - name: "Scan Virus"
        uses: "hugoalh/scan-virus-ghaction/clamav@v0.16.0"
        with:
          input_listdelimiter: "\\r?\\n"
          targets: "${{fromJson(matrix.group).uris}}"
          log_elements: "None"
