name: "Scan Virus - Specify NPM Packages"
on:
  workflow_dispatch:
    inputs:
      targets:
        description: "{String[]} Targets."
        required: true
jobs:
  parse-targets:
    name: "Parse Targets"
    runs-on: "ubuntu-latest"
    steps:
      - run: |
          $Script:ErrorActionPreference = 'Stop'
          [String[]]$NPMPackagesRaw = '${{github.event.inputs.targets}}' -isplit ";|\r?\n"
          [String[]]$NPMPackages = $NPMPackagesRaw | ForEach-Object -Process {
            Return $_.Trim()
          } | Where-Object -FilterScript {
            Return ($_ -imatch '^.+$')
          }
          [String[]]$NPMPackagesURL = @()
          ForEach ($NPMPackage In $NPMPackages) {
            Try {
              ((Invoke-WebRequest -Method Get -Uri "https://registry.npmjs.org/$NPMPackage" -UseBasicParsing).Content | ConvertFrom-Json -Depth 100).versions.PSObject.Properties | ForEach-Object -Process {
                $NPMPackagesURL += $_.Value.dist.tarball
              }
            } Catch {
              Write-Warning -Message "NPM package ``$NPMPackage`` not found!`n$($_.Exception.Message)"
              Continue
            }
          }
          If ($NPMPackagesURL.Count -igt 0) {
            Write-Host -Object "::set-output name=targets::$($NPMPackagesURL -join ';')"
          } Else {
            Throw 'No URL resolved!'
          }
        id: "parser"
        shell: "pwsh"
    outputs:
      targets: "${{steps.parser.outputs.targets}}"
  scan-virus-specify-npm-packages:
    name: "Scan Virus - Specify NPM Packages"
    runs-on: "ubuntu-latest"
    needs:
      - "parse-targets"
    steps:
      - name: "Scan NPM Packages"
        uses: "hugoalh/scan-virus-ghaction@main"
        with:
          targets: "${{needs.parse-targets.outputs.targets}}"
