name: "Scan Virus - Specify GitHub Repositories"
on:
  workflow_dispatch:
    inputs:
      targets:
        description: "{String[]} Targets."
        required: true
jobs:
  parse-targets:
    name: "Parse Targets"
    runs-on: "ubuntu-latest"
    steps:
      - run: |
          $Script:ErrorActionPreference = 'Stop'
          [String[]]$GitHubRepositoriesRaw = '${{github.event.inputs.targets}}' -isplit ";|\r?\n"
          [String[]]$GitHubRepositories = $GitHubRepositoriesRaw | ForEach-Object -Process {
            Return $_.Trim()
          } | Where-Object -FilterScript {
            Return ($_ -imatch '^.+$')
          }
          If ($GitHubRepositories.Count -igt 0) {
            Write-Host -Object "::set-output name=targets::{`"repositories`":[`"$($GitHubRepositories -join '","')`"]}"
          } Else {
            Throw 'No repository resolved!'
          }
        id: "parser"
        shell: "pwsh"
    outputs:
      targets: "${{steps.parser.outputs.targets}}"
  scan-virus-specify-github-repositories:
    name: "${{matrix.repositories}}"
    runs-on: "ubuntu-latest"
    needs:
      - "parse-targets"
    strategy:
      matrix: "${{fromJSON(needs.parse-targets.outputs.targets)}}"
      fail-fast: false
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v3.3.0"
        with:
          repository: "${{matrix.repositories}}"
          token: "${{secrets.GHP_SCANVIRUSCLONEREPOSITORY}}"
          fetch-depth: 0
      - name: "Scan Virus"
        uses: "hugoalh/scan-virus-ghaction@main"
        with:
          git_integrate: "True"
          git_reverse: "True"
