name: "Test - Build"
on:
  workflow_dispatch:
    inputs:
      git_integrate:
        description: "{Boolean} Whether to integrate with Git to perform scan by the commits."
        required: false
        default: "True"
      git_reverse:
        description: "{Boolean} Whether to reverse the scan order of the Git commits."
        required: false
        default: "False"
jobs:
  test-build:
    name: "Test - Build"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v3.4.0"
        with:
          fetch-depth: 0
      - name: "Scan Repository"
        uses: "hugoalh/scan-virus-ghaction/use/docker-build@main"
        with:
          git_integrate: "${{github.event.inputs.git_integrate}}"
          git_reverse: "${{github.event.inputs.git_reverse}}"
          clamav_unofficialsignatures: |
            ^.+$
          yara_enable: "True"
          yara_rules: |
            ^.+$
