name: "Test - Build"
on:
  workflow_dispatch:
    inputs:
      git_integrate:
        type: "boolean"
        description: "{Boolean} Whether to integrate with Git to perform scan by the commits."
        required: false
        default: true
      git_limit:
        type: "number"
        description: "{UInt} Limit on how many Git commits will scan."
        required: false
        default: 0
      git_reverse:
        type: "boolean"
        description: "{Boolean} Whether to reverse the scan order of the Git commits."
        required: false
        default: false
      yara_enable:
        type: "boolean"
        description: "{Boolean} Whether to use YARA."
        required: false
        default: false
jobs:
  test-build:
    name: "Test - Build"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v3.5.2"
        with:
          fetch-depth: 0
      - name: "Scan Repository"
        uses: "hugoalh/scan-virus-ghaction/use/docker-build@main"
        with:
          git_integrate: "${{github.event.inputs.git_integrate}}"
          git_limit: "${{github.event.inputs.git_limit}}"
          git_reverse: "${{github.event.inputs.git_reverse}}"
          clamav_unofficialassets: |-
            ^.+$
          yara_enable: "${{github.event.inputs.yara_enable}}"
          yara_unofficialassets: |-
            ^.+$
