# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Test - Build"
on:
  workflow_dispatch:
    inputs:
      git_integrate:
        type: "choice"
        description: "{Boolean} Whether to integrate with Git to perform scan by the commits."
        required: false
        default: "True"
        options:
          - "False"
          - "True"
      git_limit:
        type: "string"
        description: "{UInt} Limit on how many Git commits will scan."
        required: false
        default: "0"
      git_reverse:
        type: "choice"
        description: "{Boolean} Whether to reverse the scan order of the Git commits."
        required: false
        default: "False"
        options:
          - "False"
          - "True"
      tool_all:
        type: "boolean"
        description: "{Switch} All."
        default: true
      tool_clamav:
        type: "boolean"
        description: "{Switch} ClamAV."
        default: true
      tool_yara:
        type: "boolean"
        description: "{Switch} YARA."
        default: true
jobs:
  all:
    name: "All"
    if: "${{inputs.tool_all == true}}"
    runs-on: "ubuntu-latest"
    steps:
      - name: "List Docker Image"
        run: |
          docker image ls --all --digests --no-trunc
      - name: "Checkout Repository"
        uses: "actions/checkout@v4.1.0"
        with:
          fetch-depth: 0
      - name: "Scan Repository"
        uses: "hugoalh/scan-virus-ghaction/_build/all@main"
        with:
          git_integrate: "${{github.event.inputs.git_integrate}}"
          git_limit: "${{github.event.inputs.git_limit}}"
          git_reverse: "${{github.event.inputs.git_reverse}}"
          clamav_unofficialassets: |-
            .+
          yara_enable: "True"
          summary_found: "None"
          summary_statistics: "Clone"
  clamav:
    name: "ClamAV"
    if: "${{inputs.tool_clamav == true}}"
    runs-on: "ubuntu-latest"
    steps:
      - name: "List Docker Image"
        run: |
          docker image ls --all --digests --no-trunc
      - name: "Checkout Repository"
        uses: "actions/checkout@v4.1.0"
        with:
          fetch-depth: 0
      - name: "Scan Repository"
        uses: "hugoalh/scan-virus-ghaction/_build/clamav@main"
        with:
          git_integrate: "${{github.event.inputs.git_integrate}}"
          git_limit: "${{github.event.inputs.git_limit}}"
          git_reverse: "${{github.event.inputs.git_reverse}}"
          clamav_unofficialassets: |-
            .+
          log_elements: "OnlyCurrent"
          summary_found: "Clone"
          summary_statistics: "Clone"
  yara:
    name: "YARA"
    if: "${{inputs.tool_yara == true}}"
    runs-on: "ubuntu-latest"
    steps:
      - name: "List Docker Image"
        run: |
          docker image ls --all --digests --no-trunc
      - name: "Checkout Repository"
        uses: "actions/checkout@v4.1.0"
        with:
          fetch-depth: 0
      - name: "Scan Repository"
        uses: "hugoalh/scan-virus-ghaction/_build/yara@main"
        with:
          git_integrate: "${{github.event.inputs.git_integrate}}"
          git_limit: "${{github.event.inputs.git_limit}}"
          git_reverse: "${{github.event.inputs.git_reverse}}"
          log_elements: "OnlyCurrent"
          summary_found: "None"
          summary_statistics: "Clone"
